[package]
name = "chksum"
version = "0.4.7"
authors = ["jens"]
edition = "2021"

[dependencies]
sha2 = "0.10.8"
clap = "4.4"
walkdir = "^2.4"
blake3 = "1.5"
time = { version = "0.3.31", features = ["formatting"] }
# log = "0.4.20"
rayon = "1.8.0"
filetime = "0.2.23"
